### ISSUE TITLE
Mock remote service calls in tests

### ISSUE THREAD

**Issue by widdowquinn** [widdowquinn/ncfp#17]
#### Summary:
CircleCI weekly tests are failing when making remote service calls. These can be mocked to avoid those errors.

**Comment by widdowquinn** [comment]
Entrez tests failed again 2021-07-10. Not all Entrez-facing functions were covered in #19.

**Comment by widdowquinn** [comment]
Example CircleCI failure traceback:

```bash
Traceback (most recent call last):
  File "/home/circleci/repo/ncbi_cds_from_protein/entrez.py", line 299, in esearch_with_retries
    handle = Entrez.esearch(db=dbname, term=query_id)
  File "/home/circleci/.pyenv/versions/3.9.5/lib/python3.9/site-packages/Bio/Entrez/__init__.py", line 242, in esearch
    return _open(cgi, variables)
  File "/home/circleci/.pyenv/versions/3.9.5/lib/python3.9/site-packages/Bio/Entrez/__init__.py", line 606, in _open
    handle = urlopen(cgi)
  File "/home/circleci/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/home/circleci/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/home/circleci/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/home/circleci/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/home/circleci/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/home/circleci/.pyenv/versions/3.9.5/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 429: Too Many Requests
```
