### ISSUE TITLE
List index out of range when processing sequences

### ISSUE THREAD

**Issue by widdowquinn** [widdowquinn/ncfp#44]
#### Summary:

An error is thrown when processing sequences:

```bash
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Initialising cache...
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Setting up SQLite3 database cache at caches/new_ncfpnew/ncfpcache_ncfp_cache.sqlite3...
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Parsing sequence input...
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Reading sequences from ncfp_error_2.fasta
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: 8 sequence records read successfully from ncfp_error_2.fasta
[INFO] [ncbi_cds_from_protein.sequences]: Processing sequences...
1/5 Process input sequences:  25%|█████████████████████████████████████████████████▊                                                                                                                                                     | 2/8 [00:01<00:03,  1.83it/s]
Traceback (most recent call last):
  File "/opt/anaconda3/envs/ncfp_py311/bin/ncfp", line 33, in <module>
    sys.exit(load_entry_point('ncfp', 'console_scripts', 'ncfp')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lpritc/Documents/Development/GitHub/ncfp/ncbi_cds_from_protein/scripts/ncfp.py", line 333, in run_main
    qrecords, qskipped = process_sequences(
                         ^^^^^^^^^^^^^^^^^^
  File "/Users/lpritc/Documents/Development/GitHub/ncfp/ncbi_cds_from_protein/sequences.py", line 145, in process_sequences
    qstring = result.split("\n")[1].strip()[:-1]
              ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

#### Description:

Sequences for which `ncfp` should retrieve a corresponding nucleotide sequence are throwing an error.

#### Reproducible Steps:

With the file `ncfp_error_2.fsata`:

```text
>tr|A0A369NYJ2|A0A369NYJ2_9ACTN/284-302 Ammonium transporter OS=Adlercreutzia equolifaciens subsp. celatus OX=394340 GN=C1850_06480 PE=3 SV=1 A0A369NYJ2_Helix_8
LVGAATGLVAGLVAITPAA
>tr|A0A3N0AQL8|A0A3N0AQL8_9ACTN/284-302 Ammonium transporter OS=Adlercreutzia equolifaciens subsp. celatus DSM 18785 OX=1121021 GN=DMP10_09225 PE=3 SV=1 A0A3N0AQL8_Helix_8
LVGAATGLVAGLVVITPAA
>tr|A0A6I8TEK7|A0A6I8TEK7_AEDAE/292-312 Ammonium transporter OS=Aedes aegypti OX=7159 GN=5569115 PE=3 SV=1 A0A6I8TEK7_Helix_8
IVDLINGILASLVSVTAGCFL
>tr|A0A6I8TEI4|A0A6I8TEI4_AEDAE/289-309 Ammonium transporter OS=Aedes aegypti OX=7159 GN=5569115 PE=3 SV=1 A0A6I8TEI4_Helix_8
IVDLINGILASLVSVTAGCFL
>tr|Q1L727|Q1L727_AEDAE/285-303 Ammonium transporter OS=Aedes aegypti OX=7159 PE=2 SV=1 Q1L727_Helix_8
IMNGVLASLVSVTGGCYLF
>tr|A0A1S4FGA3|A0A1S4FGA3_AEDAE/292-310 AAEL007377-PA OS=Aedes aegypti OX=7159 GN=AAEL007377 PE=4 SV=1 A0A1S4FGA3_Helix_8
IMNGVLASLVSVTGGCYLF
>tr|E2SD44|E2SD44_9ACTN/268-285 Ammonium transporter OS=Aeromicrobium marinum DSM 15272 OX=585531 GN=amt PE=3 SV=1 E2SD44_Helix_8
KATAVGAASGVVTGLVAI
>tr|E2SD33|E2SD33_9ACTN/260-277 Ammonium transporter OS=Aeromicrobium marinum DSM 15272 OX=585531 GN=amt PE=3 SV=1 E2SD33_Helix_8
LGAASGAIAGLVAVTPAA
```

and the command

```bash
ncfp --unify_seqid -s -v -l ncfp_error_2.log ncfp_error_2.fasta ncfp_error_2.out me@dev.null -d caches/new_ncfpnew -c ncfp_cache
```

the error above is thrown

**Comment by widdowquinn** [comment]
This issue arises due to an update in the `bioservices` package. Briefly, where UniProt queries would return `<FIELD>\n<VALUE>\n` if there was a match, and `<FIELD>\n\n` if not, they now return `<FIELD>` (no newlines) if there is no match.
